\begin{frame}[fragile]{Makefile (partie 1)}
\vspace{-1em}
\inputminted[
  firstline=1,
  lastline=30,
  breaklines=true,
  fontsize=\tiny,
  frame=lines,
  framesep=1mm
]{c}{../Makefile}
\end{frame}

\begin{frame}[fragile]{Makefile (partie 2)}
\vspace{-1em}
\inputminted[
  firstline=31,
  lastline=59,
  breaklines=true,
  fontsize=\tiny,
  frame=lines,
  framesep=1mm
]{c}{../Makefile}
\end{frame}

